### ISSUE TITLE
Missing npy files

### ISSUE THREAD

**Issue by hassantsyed** [jiawei-ren/insactor#2]
Hi Jiawei,

Amazing project you all have built here.

I am following the instructions to run, and I get this error:
FileNotFoundError: [Errno 2] No such file or directory: 'data/datasets/human_pml3d/mean.npy'
File "/content/insactor/tools/demo_utils/diffuse.py", line 15, in <module>
    mean = np.load(mean_path)

It seems like these files are missing
mean_path = "data/datasets/human_pml3d/mean.npy"
std_path = "data/datasets/human_pml3d/std.npy"

They are referenced in tools/demo_utils/diffuse.py
https://github.com/jiawei-ren/insactor/blob/8bd64ee3553d51963314366a16488c2c01b2acbb/tools/demo_utils/diffuse.py#L10

Can you include these files, or is there something I am missing from the instructions?
Thanks!

**Comment by jiawei-ren** [comment]
Hi Hassan,

Thanks for raising the issue! I have uploaded them to assets please give it a try.
